### PR TITLE
Adds a way to add fallbacks.

### PR DESCRIPTION
**Pull request by goddessfreya**
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

### CODE REVIEW

**Comment by kvark** [comment]
Let's make CI happy, shall we? :)

**Comment by tomaka** [comment]
Does that mean that the user can do `function.is_loaded = false;` or `function.is_loaded = true;`. Is that something we want?

**Comment by brendanzab** [comment]
Can't one call the `.is_loaded()` methods? That's why I added them! 😅

**Comment by ZeGentzy** [comment]
Fixed. Sorry for not testing (or waiting for the CI to finish).

**Pull request closed without merging**
